### ISSUE TITLE
Force `[NewObject]` for Promise returning functions?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/webidl#1084]
Currently some functions have `[NewObject]` and some are not, e.g.:

* Fetch has `[NewObject]` everywhere https://fetch.spec.whatwg.org/#body-mixin
* ... while Push does not https://w3c.github.io/push-api/#pushmanager-interface

But that's weird, since those always do return a new Promise object. Should it be forced?

**Comment by saschanaz** [comment]
In the same sense, maybe force `[SameObject]` for `readonly attribute Promise<T>`?

**Comment by annevk** [comment]
I could imagine a collection of promises with a `get()` method that would return the same promise, depending on the arguments passed.

Similarly, I think we have cases where attributes can return a new promise after the corresponding object has undergone a (fundamental) state change.

So unfortunately I don't think there's a hard-and-fast rule here, but it's something to be looked at on a case-by-case basis.

**Comment by domenic** [comment]
Some of this may be a symptom of how I tend to discourage any use of [NewObject]/[SameObject] in specs I review and mentor, since they are just documentation that is easy to get out of sync with the normative algorithms. (See previous discussions about some new version of [SameObject] which has normative power...)

**Comment by saschanaz** [comment]
Oh yeah, there's #212 for example.

**Comment by saschanaz** [comment]
Closing this in favor of #212
