### ISSUE TITLE
An undefined dictionary member in IDL->JS conversion: exist or not?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/webidl#1094]
The Streams spec has [the following dictionary](https://streams.spec.whatwg.org/#dictdef-readablestreambyobreadresult):

```webidl
dictionary ReadableStreamBYOBReadResult {
  ArrayBufferView value;
  boolean done;
};
```

Here, `value` can be an ArrayBufferView or undefined per the relevant algorithms:

* https://streams.spec.whatwg.org/#byob-reader-read, "given chunk" in "close steps"
* Where the "chunk" can be undefined https://streams.spec.whatwg.org/#read-into-request-close-steps

And there's relevant WPT tests that checks the existence of `value` field even when it's `undefined`. https://github.com/web-platform-tests/wpt/blob/62c22e4362e19418022e03ca4f5bea76b998fa3f/streams/readable-byte-streams/tee.any.js#L503

And here's my question: does the IDL spec allows an `undefined` field as a result of IDL->JS conversion? And if it does, should it? (I mean, `{ done: true }` or `{ value: undefined, done: true }`)?

**Comment by saschanaz** [comment]
After a talk with @petervanderbeken I believe the IDL dictionary can't have an undefined field (in other words, if `V[key] exists` then it means a non-undefined value, unless the type of the field has `undefined`).

cc @MattiasBuelens who wrote the test and edits the spec; Do you perhaps have a counterargument? 👀

**Comment by MattiasBuelens** [comment]
The Streams standard aims to align the return value of `reader.read()` with the return value of `iterator.next()`.
```javascript
let array = ["a", "b"];
let it = array[Symbol.iterator]();
it.next(); // { done: false, value: "a" }
it.next(); // { done: false, value: "b" }
it.next(); // { done: true, value: undefined }

let readable = new ReadableStream({
  start(c) {
    c.enqueue("a");
    c.enqueue("b");
    c.close();
  }
});
let reader = readable.getReader();
await reader.read(); // { done: false, value: "a" }
await reader.read(); // { done: false, value: "b" }
await reader.read(); // { done: true, value: undefined }
```

Before we switched to Web IDL in https://github.com/whatwg/streams/commit/caf3cea28134d8be2ec69b6a1105748a7c8d10b5, we tried to match this by having [ReadableStreamCreateReadResult](https://streams.spec.whatwg.org/commit-snapshots/cfcd303a38158e4ec3837d1028158c88d505c35d/#readable-stream-create-read-result) behave the same as ECMAScript's [CreateIterResultObject](https://tc39.es/ecma262/#sec-createiterresultobject). So a read result would *always* have `done` and `value` properties, even if the latter were `undefined`.

Today in Web IDL, the same CreateIterResultObject function is used to [construct an iterator result](https://webidl.spec.whatwg.org/#iterator-result). So that *also* always has both properties, but it isn't used to construct a `read()` result.

I don't know whether it's acceptable to return `{ done: true }` instead of `{ done: true, value: undefined }`. One can argue that matching the return values of `iterator.next()` is less important now that [`ReadableStream` has its own dedicated async iterator](https://streams.spec.whatwg.org/#rs-asynciterator). But then again, we've had `{ done: true, value: undefined }` on `read()` for a while now, and it might be too late to change it.

@domenic @ricea What are your thoughts on this?

---

Alternatively, would this be allowed?
```
dictionary ReadableStreamBYOBReadResult {
  (ArrayBufferView or undefined) value;
  boolean done;
};
```
That would more closely match our current behavior.

**Comment by domenic** [comment]
Yes, I think using `(ArrayBufferView or undefined)` is the way to go, or if that doesn't work for some reason then using `any` since this is just a return-value dictionary and so its IDL types don't really matter.

We should have both properties.

**Comment by saschanaz** [comment]
Closing as the spec is now fixed.

**Comment by petervanderbeken** [comment]
> Yes, I think using `(ArrayBufferView or undefined)` is the way to go, or if that doesn't work for some reason then using `any` since this is just a return-value dictionary and so its IDL types don't really matter.

@domenic I had forgotten about this too, but the WebIDL spec currently disallows `undefined` in dictionary members (directly or in a union), so sadly I think the only valid option would be `any`.

**Comment by saschanaz** [comment]
Ah, makes sense. I can open another PR to do `any`.

(...although I think that limitation is more for dictionary-as-argument case than as-return-type case. Should there be a separate dictionary type for returns? 😄)
