### ISSUE TITLE
ExtendedAttributeList can match unbalanced ( ), [ ], and { }

### ISSUE THREAD

**Issue by jeremydavis519** [whatwg/webidl#1100]
There's a note at the bottom of the [IDL grammar](https://webidl.spec.whatwg.org/#idl-grammar) section that says the following:

> Note: The [_Other_](https://webidl.spec.whatwg.org/#prod-Other) non-terminal matches any single terminal symbol except for **(**, **)**, **[**, **]**, **{**, **}** and **,**.

This is false, since one production of that non-terminal is the [**other**](https://webidl.spec.whatwg.org/#prod-other) terminal, defined as `/[^\t\n\r 0-9A-Za-z]/`, which definitely does match those characters. At the same time, the note clearly matches the intended behavior, since allowing _Other_ to match brackets means that finding the end of a set of extended attributes is impossible for a spec-compliant parser.

It looks like nothing besides extended attributes uses the **other** terminal symbol, so my proposed fix is to change its definition to this regular expression:
`/[^\t\n\r 0-9A-Za-z()\[\]{},]/`

I'm sure every existing IDL parser does the right thing in this matter (they'd be utterly broken otherwise), but the specification should also be correct.

_Edit:_ After further consideration, I now realize that the normative text does disallow using the **other** terminal rule on any token that could be matched by something else, so spec-compliant parsers will find the closing **]** in the [*ExtendedAttributeList*](https://webidl.spec.whatwg.org/#index-prod-ExtendedAttributeList) rule. But unless I'm reading it wrong, the standard as written does allow that rule to match things like `[(]`, `[)]`, and `[{]}]`, which seems like it might be a bug.

**Comment by bathos** [comment]
The note is using "terminal symbol" where it means "literal source text string that a terminal symbol can match". IIRC this terminology fuzziness happens somewhere else, too.

**Comment by jeremydavis519** [comment]
I guess that's true (and now that you mention it, that's started bugging me a little), but my point is that the normative text doesn't match what seems to be the intended behavior. As I noted in the edit, the grammar as written allows the parser to match unbalanced parentheses, brackets, and braces in extended attributes, at least in the super-permissive _ExtendedAttributeList_ rule. It probably doesn't change any actual behavior, since extended attributes undergo more parsing later on, but I think it's still worth fixing.

In retrospect, I buried the lead a little. I'm changing the issue name to better reflect the problem.

**Comment by bathos** [comment]
Hm ... are you maybe under the impression that _other_ literally includes `[` etc? It doesn't: the regexps are "starting points" only. Each time a literal teletype terminal appears in the syntactic grammar, it "creates" a new "anonymous" terminal that doesn't match any of the "named" terminals.

**Comment by jeremydavis519** [comment]
Hm... I think I understand now. Thanks. And you're right that it's really unclear that that's how it works.

So, when the standard says, "When tokenizing, the longest possible match must be used," it means the longest possible match _regardless of where that match appears in the grammar_? I took it to mean only the longest possible match that could appear in that position, given all the earlier tokens. But I guess the examples right after that statement don't have that limitation. And this does all match the usual model that separates the tokenizer and the parser.

So it looks like the text is technically accurate, but for clarity I'd add a note after the examples of what is not an **identifier** to mention that it doesn't matter what rule is being matched when the token is found. Does that sound reasonable? It definitely would have helped me make sense of this, and I imagine other people have been confused in the same way.

**Comment by bathos** [comment]
Yes, exactly, it's unambiguously _derivable_ from the given facts ... but it's a bit of a journey to get there! I agree that a note would help future readers.

FWIW, I also got caught by this when I first started working w/ the Web IDL grammar, and there's a fair amount of evidence that it's confused other folks too. It's a hazard when editors add new keywords because it's not obvious that the act of adding a new keyword in a specific production also removes that literal source text string from `identifier`, affecting any number of other nonterminals one did not realize they were also editing!

The benefit, I think, is that this model effectively elevates "keywords" to a concern of the lexical grammar. This is kinda cool; it means there's (almost) no "static semantics" style rules needed to constrain identifiers extra-grammatically. The BNF-ish rules encode it directly instead. (The exceptions are cases where it's the string value of the ID that matters, e.g. "constructor" cannot be an operation name even if escaped with the underscore prefix.)

The biggest clue about the existence of this behavior is probably the nonterminals like ArgumentNameKeyword. These only make sense if there are ~85 or so (I forget the exact number) unique terminal symbols, not 7: all of their alternatives match the "initial" `identifier` regexp.

To save you from possibly having to figure out the next "wait, huh?" step of this lil journey, you may want to check out #812. The intuitive approach to lexing is to still use the seven "named" terminal patterns and then map their symbolic identities after with a static table, but there is one "anonymous" terminal that this approach will miss.

**Comment by bathos** [comment]
(I believe this issue can be closed unless it’s desired to treat it as a request for clearer/more prominent specification text regarding the nature of the lexical grammar.)
