### ISSUE TITLE
Replaceable attribute `window.performance`

### ISSUE THREAD

**Issue by legendecas** [whatwg/webidl#1193]
https://webidl.spec.whatwg.org/#Replaceable defines that a replaceable attribute should be an IDL attribute (accessor pair defined on the prototype instead of the instance objects), whilst it can be replaced with shadowing the prototype accessor when setting the corresponding property on the platform object, like the https://webidl.spec.whatwg.org/#example-fe2bdbf4 shows.

[`window.performance`](https://www.w3.org/TR/hr-time-3/#the-performance-attribute) is defined as a replaceable attribute on WindowOrWorkerGlobalScope. Major browser implementations (Chrome, Safari, Firefox) seem to be diverging from the definition of a replaceable attribute:

```js
window. hasOwnProperty('performance'); // => true, should be false according to the definition.
Object.getPrototypeOf(window).hasOwnProperty('performance'); // => false, should be true
```

Is this an implementation bug, or should we update the spec to reflect what the reality is?

Refs: https://github.com/nodejs/node/pull/44483#discussion_r961088430

**Comment by petervanderbeken** [comment]
> ```js
> window. hasOwnProperty('performance'); // => true, should be false according to the definition.
> ```

Interface members for interface marked with `[Global]` are properties on the instance object instead of on the interface prototype object. (see https://webidl.spec.whatwg.org/#es-attributes and step 10 in https://webidl.spec.whatwg.org/#es-platform-objects). `[Replaceable]` really only changes the behaviour of the attribute's setter (see step 4.5.5 in https://webidl.spec.whatwg.org/#dfn-attribute-setter).

**Comment by legendecas** [comment]
Thank you for the clarification.
