### ISSUE TITLE
Float16Array integration

### ISSUE THREAD

**Issue by bathos** [whatwg/webidl#1310]
Integrating [Float16Array](https://github.com/tc39/proposal-float16array) into Web IDL looks very straightforward (it effectively amounts to inserting `Float16Array` before every `Float32Array` in the text, sometimes with a comma), but I figured it deserved a tracking issue here given the proposal is at stage 3 now.

**Comment by Josh-Cena** [comment]
@bakkot I have a question about float16 x WebIDL: is there a numeric type for float16, like `unrestricted float` and `unrestricted double`?

**Comment by bakkot** [comment]
@Josh-Cena There is not such a type as far as I know. As to whether it would be useful - maybe? The only potential consumers I'm aware of are [WebNN](https://www.w3.org/TR/webnn/#api-mloperanddescriptor) and [high-bit-depth canvases](https://github.com/w3c/ColorWeb-CG/blob/main/canvas_float.md), and I'm not sure either of them actually need float16 values. I think it can wait until someone actually needs it.

**Comment by Josh-Cena** [comment]
Okay, thanks for confirming.

**Comment by inexorabletash** [comment]
Re: WebNN: At this point we don't anticipate needing a type in WebIDL for float16, since API methods each accept a wide variety of data types, and in all cases the data type is either explicitly given as sibling argument or implicit based on other inputs. When dealing with float16 data, callers are either passing a `Float16Array` (a "tensor") into a method defined in WebIDL to accept an `ArrayBufferView`, or a single ("scalar") value where the method would take either a `double` (caller passes a JS number) or a `(double or bigint)` (caller passes a JS number or BigInt) and then it is internally down-cast as needed to float16. 

There's a very very draft PR of what this might look like in https://github.com/webmachinelearning/webnn/pull/647 - this sketches out some of the casting that might be needed. Since some of the conversion logic duplicates stuff in WebIDL it could be nice to refactor and export some of the WebIDL abstract operations, but (1) it's premature to do so now and (2) even if done we'd just need the operations, not a defined `half` or `unrestricted half` type.
