### ISSUE TITLE
Intent use number / bigint union type

### ISSUE THREAD

**Issue by sbc100** [whatwg/webidl#1426]
In WebAssembly we are planning on using the union of long long and bigint: https://github.com/WebAssembly/memory64/pull/75

In accordance with the warning in https://webidl.spec.whatwg.org/#idl-union we are opening this issue.

I believe that our use case doesn't run into any issues because we are essentially implementing overloading based on the type of the receiver.  The receiver is either a 64-bit memory/table (in which case we expect bitint indexes) or a 32-bit memory/table (in which case we expect number indexes).

**Comment by sbc100** [comment]
CC @littledan who added the wording about these union types.

**Comment by annevk** [comment]
I'd be curious to hear @littledan's take, but this seems reasonable to me. Thanks for filing!

**Comment by sbc100** [comment]
Closing this since we have gone ahead with this change now on the wasm side.

**Comment by bvisness** [comment]
FYI, we ended up reverting this in https://github.com/WebAssembly/memory64/pull/86 because the special [conversion rules](https://webidl.spec.whatwg.org/#js-bigint) for a union of numeric type and bigint would, through [ToNumeric](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tonumeric)/[ToNumber](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tonumber), force all string and boolean values to be interpreted as Number instead of BigInt. This is a very confusing special case.
