### ISSUE TITLE
Absence of "record" token from Other production

### ISSUE THREAD

**Issue by bathos-wistia** [whatwg/webidl#694]
It appears that the token "record" is absent from the [Other production](https://heycam.github.io/webidl/#index-prod-Other). This seems to make the ExtendedAttribute cover grammar fail for examples like [URLSearchParams](https://url.spec.whatwg.org/#interface-urlsearchparams). The text in the grammar section seems to indicate the identifier token is not inclusive of any terminals that get explicitly indicated in the grammar, which is consistent with the fact that most other keywords do get listed (directly or indirectly) in Other.

Is the absence of “record” accidental, intentional, or am I misinterpreting something?

**Comment by bzbarsky** [comment]
I don't think you're misinterpreting something, and this is accidental.

**Comment by bathos** [comment]
This got fixed at some point. I opened this issue a few years ago while logged in with an old work-specific account, so I can't close it myself any more, but any org member should feel free to do so. (e.g. @annevk ?)

_(For the small chance of someone coming across this issue in the future and getting confused by the example link: at the time this issue was opened, constructors signatures were still declared using extended attributes)._
