### ISSUE TITLE
What is "type name" used for?

### ISSUE THREAD

**Issue by domenic** [whatwg/webidl#835]
https://heycam.github.io/webidl/#dfn-type-name defines the concept and every type gives how to construct their type name. But, nothing else in the spec seems to use it. What is it for?

**Comment by bzbarsky** [comment]
The only use I am aware of offhand is error messages from an IDL parser or compiler...

**Comment by domenic** [comment]
Heh, I suspected something like that. Would it make sense to remove it? Or we could just add an explanation to its definition that it is not web-observable and is meant for purposes such as that.

**Comment by bzbarsky** [comment]
I'm probably fine either way.

**Comment by annevk** [comment]
https://heycam.github.io/webidl/#es-buffer-source-types seems to use it for something normative looking?

**Comment by bathos** [comment]
@annevk It’s probably also worth factoring out it’s confusing that type names aren’t guaranteed to be unique. In that algorithm it’s safe to rely on the names because you wouldn’t enter it in the first place unless type type in question were a real typed array type, but it’s still super weird that we can create other types with (e.g.) the type name _Int8Array_ by other means:

1. Escape an interface name:

```
interface _Int8Array {};
```

2. Frozen array shenanigans:

```
interface Int8 {};
typedef FrozenArray<Int8> lol;
```

**Comment by bathos** [comment]
Yep. FWIW, that’s what the first sentence of that comment said too — the examples were meant to show that non-unique type name derivations might be surprising or confusing as opposed to unsound.
